---
layout: post
title: Exception Handling
categories: 编程语言
---

### Introduction

操作系统中的异常与编程语言中的异常不同：
* 编程语言中使用的 throw 语句，将控制权转移到匹配的 catch clause
* throw 抛出的异常可能被当前方法的 catch 子句捕获，或者被调用方法的 catch 子句捕获。
* throw 语句唯一的作用就是跳转到 catch 子句

jump statement:
* throw: passes control to a matching catch clause
* break: jumps to th end of a block in the same method
* return: jumps to the next statement in the calling method

abruptly complete:
* 如果语句的正常执行被 brek、continue、return、goto 语句打乱，叫做突然完成

### Java 中的异常

异常的种类：
* 异常用类 Throwable 或其子类的实例所表示
* `Throwable` 和所有的子类，都叫做异常类 (exception classes)
* `Exception` 和 `Error` 是 Throwable 的直接子类
    * **Exception 类**
        - 程序可能会从其中恢复过来的所有异常的超类
        - `RuntimeException` 是 Exception 的直接子类
        - RuntimeException 是以下异常的超类，异常产生于表达式评估过程并且可能从中恢复
        - RuntimeException 类和所有的子类，叫做 run-time exception classes
    * **Error 类**
        - 程序一般无法从中恢复过来的异常的超类
        - Error 和所有的子类，叫做 error classes
* **unchecked exception classes**: 包含 run-time exception classes 和 error classes
* checked exception classes：除了 unchecked exception classes 其余的类

异常的原因：
* throw statement
* JVM 检测到了非正常的执行条件
    - 例如要评估的表达式违反了正常的 semantics，比如整数除以 0
    - 在加载、链接、处理化时发生错误
    - 网络错误、资源限制
* 异步异常发生

编译时异常检查：
* Java 要求程序包含 checked exceptions 的处理程序
* 但是 unchecked exception classes 在编译时不进行检查的
    - Error 不进行检查时因为很难从中恢复
    - run-time exception 是因为声明此异常不会显著增加程序的正确性。

异常的运行时处理：
* 当异常被抛出，控制从造成异常的代码转移到最近的动态附加的 catch 子句。
* 语句或表达式是 dynamically enclosed by a catch clause，如果它出现在 try block 里，或者调用者是 dynamically enclosed by the catch clause
* 控制的转移造成表达式或者语句的 abrupt completion，直到遇到可以处理该异常的 catch cluase，接下来就会执行 catch 子句块。造成异常的代码永远不会继续执行。
* 如果找不到可以处理异常的 catch 子句，那么当前的线程会被终止。线程终止之前，
* 所有的 finally clauses 被执行

throw 语句：
* 抛出异常，结果是控制的转移，直到找到可以捕获该异常的 try 语句。
* 如果找不到这样的 try 语句，线程组调用 uncaughtException 方法后线程被终止，

try 语句：
* 执行一个 block。
* 如果try 语句有一个或多个可以捕获该异常的 catch 子句，控制被转移到第一个 catch 子句。
* 如果 try 语句有 finally 子句，那么另一个代码块被执行，无论 try block 正常完成或者中断，无论是否有 catch 子句获得了控制。

try-catch 的执行：
* 如果 try block 正常完成，那么没有别的动作，try 语句正常完成
* 如果在执行 try block 时由于 throw 一个值 v 而突然完成，那么有以下选择：
    - 如果运行时类型 v 是一个可以被 try 语句的任一 catch 子句捕获的异常，那么该 catch block 执行
        - 如果 block 正常完成，try 语句正常完成
        - 如果 block 由于任何原因突然完成，那么 try 语句会由于相同原因 complete abruptly 
    - 如果 v 与任何 try 语句的 catch 子句都不兼容，那么try 语句由于抛出值 v 而 complete abruptly
* 如果执行 try block 由于其他原因突然完成，那么 try 语句由于相同的原因突然完成。

try-finally 和 try-catch-finally 的执行：
* 先执行 try block
* 如果 try block 正常完成，finally block 被执行
    - 如果 finally block 正常完成，那么 try 语句正常完成
    - 如果 finally block 由于原因 s 突然完成，try 语句由于 s 突然完成
* 如果 try block 由于 throw 值 v 突然完成：
    - 如果 v 可以被捕获，那么执行 catch 子句的 block
        * 如果 catch block 正常完成，执行 finally block
            - 如果 finally block 正常完成，try 语句正常完成
            - 如果 finally block 突然完成，try 语句由于相同原因突然完成
        * 如果 catch block 由于原因 R 突然完成，执行 finally block
            - 如果 finally block 正常完成，try 语句由于原因 R 突然完成
            - 如果 finally block 由于原因 S 突然完成，那么 try 语句由于原因 S 突然完成
    - 如果 V 不能被捕获，执行 finally block
        * 如果 finally block 正常完成，try 语句由于抛出值 v 而突然完成
        * 如果 finally block 由于原因 S 突然完成，那么 try 语句由于原因 S 而突然完成
* 如果 try block 由于其他原因 R 而突然完成，执行 finally block
    - 如果 finally block 正常完成，那么 try 语句由于原因 R 正常完成
    - 如果 finally block 由于原因 S 突然完成，那么 try 语句由于原因 S 突然完成 (原因 R 被舍弃)

关于 finally 子句
- finally 会 trap 异常、任何的 jump 语句，即 finally 子句一定会执行
- 但是 finally block 中也可以包含 jump 语句，造成 finally 子句的突然完成。
- finally 子句不是异常处理的一部分，因为其无法分辨是否发生了异常。
- 最佳实践：
    * A Java finally clause should almost never contain a break, continue, or return statement and should be careful to only throw exceptions that reflect a preemptively significant problem. Normally the finally clause should perform its intended functions and then end normally, allowing the system to resume what it was doing


catch 子句结束的五种方式：
* catch 子句正常完成
    - 从 Java 角度看，throw 终止在 catch，catch 子句正常结束
* 由于执行了一个 non-throw jump 语句 (return，break，continue)，控制可能会离开 catch 子句。
    - 从 Java 角度看，catch clause 由于非 throw 原因而 "terminated abruptly"
* catch 子句可以重新抛出原始的异常对象
* catch 子句可以创建、抛出一个新的 throwable 对象，该对象链接到原始的异常
* catch 子句以 error 的方式终止



